# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.map = QtWidgets.QLabel(self.centralwidget)
        self.map.setText("")
        self.map.setObjectName("map")
        self.gridLayout.addWidget(self.map, 2, 0, 1, 3)
        self.serch_line = QtWidgets.QLineEdit(self.centralwidget)
        self.serch_line.setObjectName("serch_line")
        self.gridLayout.addWidget(self.serch_line, 0, 0, 1, 2)
        self.clear_serch = QtWidgets.QPushButton(self.centralwidget)
        self.clear_serch.setObjectName("clear_serch")
        self.gridLayout.addWidget(self.clear_serch, 0, 2, 1, 1)
        self.schematic = QtWidgets.QRadioButton(self.centralwidget)
        self.schematic.setObjectName("schematic")
        self.gridLayout.addWidget(self.schematic, 1, 0, 1, 1)
        self.satellite = QtWidgets.QRadioButton(self.centralwidget)
        self.satellite.setObjectName("satellite")
        self.gridLayout.addWidget(self.satellite, 1, 1, 1, 1)
        self.hybrid = QtWidgets.QRadioButton(self.centralwidget)
        self.hybrid.setObjectName("hybrid")
        self.gridLayout.addWidget(self.hybrid, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Yandex Maps"))
        self.clear_serch.setText(_translate("MainWindow", "Очистить"))
        self.schematic.setText(_translate("MainWindow", "Схема"))
        self.satellite.setText(_translate("MainWindow", "Спутник"))
        self.hybrid.setText(_translate("MainWindow", "Гибрид"))
